services:
 django-web:
   build: .
   container_name: digital_pathology_demo
   volumes:
     - .:/app
     - ${DJANGO_SQLITE_DIR}:/app/database
     - static_volume:/app/staticfiles
   ports:
     - "8000:8000"
   environment:
     DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
     DEBUG: ${DJANGO_DEBUG}
     DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
   env_file:
     - .env

 nginx:
   image: nginx:stable-alpine
   ports:
     - "80:80"
     - "443:443"
   volumes:
     - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
     - static_volume:/app/staticfiles:ro
     - ${NGINX_CRT}:/etc/nginx/certs/server.crt:ro
     - ${NGINX_KEY}:/etc/nginx/certs/server.key:ro
     - /var/www/certbot:/var/www/certbot:ro
   restart: unless-stopped
   environment:
     - NGINX_WORKERS=AUTO
   depends_on:
     - django-web

volumes:
 static_volume: